package io.jboot.admin.service.entity.model;

import io.jboot.admin.service.entity.status.system.DataStatus;
import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseAffectedGroup;

import java.util.Objects;

/**
 * Generated by Jboot.
 */
@Table(tableName = "affected_group", primaryKey = "id")
public class AffectedGroup extends BaseAffectedGroup<AffectedGroup> {
    public void setStatus(java.lang.String status) {
        if (Objects.equals(status, DataStatus.USED)) {
            setIsEnable(true);
        } else {
            setIsEnable(false);
        }
    }

    public java.lang.String getStatus() {
        if (this.getIsEnable()) {
            return DataStatus.USED;
        } else {
            return DataStatus.UNUSED;
        }
    }
}
