package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseAffectedGroup;

/**
 * Generated by Jboot.
 */
@Table(tableName = "affected_group", primaryKey = "id")
public class AffectedGroup extends BaseAffectedGroup<AffectedGroup> {
	
}
