package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseApplyInvite;

/**
 * Generated by Jboot.
 * @author ASUS
 */
@Table(tableName = "apply_invite", primaryKey = "id")
public class ApplyInvite extends BaseApplyInvite<ApplyInvite> {
    private String groupType;

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    private String userName;

    public String getGroupType() {
        return groupType;
    }

    public void setGroupType(String groupType) {
        this.groupType = groupType;
    }
}
