package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseApplyInvite;

/**
 * Generated by Jboot.
 * @author ASUS
 */
@Table(tableName = "apply_invite", primaryKey = "id")
public class ApplyInvite extends BaseApplyInvite<ApplyInvite> {
    private String groupType;

    public String getGroupType() {
        return groupType;
    }

    public void setGroupType(String groupType) {
        this.groupType = groupType;
    }
}
