package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseApplyInvite;

/**
 * Generated by Jboot.
 */
@Table(tableName = "apply_invite", primaryKey = "id")
public class ApplyInvite extends BaseApplyInvite<ApplyInvite> {
	
}
