package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseAuth;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_auth", primaryKey = "id")
public class Auth extends BaseAuth<Auth> {
	
}
