package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseAuthProject;

import java.util.Date;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_auth_project", primaryKey = "id")
public class AuthProject extends BaseAuthProject<AuthProject> {

    String projectName;
    String startTime;
    String entTime;

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getEntTime() {
        return entTime;
    }

    public void setEntTime(String entTime) {
        this.entTime = entTime;
    }



    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
}
