package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseAuthProject;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_auth_project", primaryKey = "id")
public class AuthProject extends BaseAuthProject<AuthProject> {

    String projectName;

    public String getProjectName() {
        return projectName;
    }

    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
}
