package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseB2cProduct;

/**
 * Generated by Jboot.
 */
@Table(tableName = "b2c_product", primaryKey = "id")
public class B2cProduct extends BaseB2cProduct<B2cProduct> {
	
}
