package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseBook;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_book", primaryKey = "id")
public class Book extends BaseBook<Book> {
	
}
