package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseDiagnoses;

/**
 * Generated by Jboot.
 */
@Table(tableName = "diagnoses", primaryKey = "id")
public class Diagnoses extends BaseDiagnoses<Diagnoses> {
	
}
