package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseEducational;

/**
 * Generated by Jboot.
 */
@Table(tableName = "educational", primaryKey = "id")
public class Educational extends BaseEducational<Educational> {
	
}
