package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseEnterprise;

/**
 * Generated by Jboot.
 */
@Table(tableName = "enterprise", primaryKey = "id")
public class Enterprise extends BaseEnterprise<Enterprise> {
	
}
