package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseEnterPrise;

/**
 * Generated by Jboot.
 */
@Table(tableName = "enterPrise", primaryKey = "id")
public class EnterPrise extends BaseEnterPrise<EnterPrise> {
	
}
