package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseEvaScheme;

/**
 * Generated by Jboot.
 */
@Table(tableName = "eva_scheme", primaryKey = "id")
public class EvaScheme extends BaseEvaScheme<EvaScheme> {

}
