package io.jboot.admin.service.entity.model;

import io.jboot.admin.service.entity.status.system.DataStatus;
import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseExpertGroup;

/**
 * Generated by Jboot.
 */
@Table(tableName = "expert_group", primaryKey = "id")
public class ExpertGroup extends BaseExpertGroup<ExpertGroup> {


}
