package io.jboot.admin.service.entity.model;

import io.jboot.admin.service.entity.model.base.BaseExpertGroup;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "expert_group", primaryKey = "id")
public class ExpertGroup extends BaseExpertGroup<ExpertGroup> {

    private boolean isInvite;

    public void setIsInvite(boolean isInvite) {
        this.isInvite = isInvite;
    }

    public boolean getIsInvite() {
        return this.isInvite;
    }

}
