package io.jboot.admin.service.entity.model;

import io.jboot.admin.service.entity.model.base.BaseExpertGroup;
import io.jboot.db.annotation.Table;

/**
 * Generated by Jboot.
 */
@Table(tableName = "expert_group", primaryKey = "id")
public class ExpertGroup extends BaseExpertGroup<ExpertGroup> {

    private User user;
    private boolean isInvite;

    public void setIsInvite(boolean isInvite) {
        this.isInvite = isInvite;
    }

    public boolean getIsInvite() {
        return this.isInvite;
    }

    public User getUser() {
        return user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    public String getUserName() {
        return user.getName();
    }
}
