package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseFacAgency;

/**
 * Generated by Jboot.
 */
@Table(tableName = "fac_agency", primaryKey = "id")
public class FacAgency extends BaseFacAgency<FacAgency> {
	
}
