package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseFileForm;

/**
 * Generated by Jboot.
 */
@Table(tableName = "file_form", primaryKey = "id")
public class FileForm extends BaseFileForm<FileForm> {
	
}
