package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseFiles;

/**
 * Generated by Jboot.
 */
@Table(tableName = "files", primaryKey = "id")
public class Files extends BaseFiles<Files> {
	
}
