package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseImpTeam;

/**
 * Generated by Jboot.
 */
@Table(tableName = "impteam", primaryKey = "id")
public class ImpTeam extends BaseImpTeam<ImpTeam> {
	
}
