package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseInformationFill;

/**
 * Generated by Jboot.
 */
@Table(tableName = "information_fill", primaryKey = "id")
public class InformationFill extends BaseInformationFill<InformationFill> {
	
}
