package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseInitialRiskExpertise;

/**
 * Generated by Jboot.
 */
@Table(tableName = "initial_risk_expertise", primaryKey = "id")
public class InitialRiskExpertise extends BaseInitialRiskExpertise<InitialRiskExpertise> {

}
