package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseLeaderGroup;

/**
 * Generated by Jboot.
 */
@Table(tableName = "leader_group", primaryKey = "id")
public class LeaderGroup extends BaseLeaderGroup<LeaderGroup> {
	
}
