package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseNation;

/**
 * Generated by Jboot.
 */
@Table(tableName = "nation", primaryKey = "id")
public class Nation extends BaseNation<Nation> {
	
}
