package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseNews;

/**
 * Generated by Jboot.
 */
@Table(tableName = "news", primaryKey = "id")
public class News extends BaseNews<News> {
	
}
