package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseNotification;

/**
 * Generated by Jboot.
 */
@Table(tableName = "notification", primaryKey = "id")
public class Notification extends BaseNotification<Notification> {
}
