package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseOccupation;

/**
 * Generated by Jboot.
 */
@Table(tableName = "occupation", primaryKey = "id")
public class Occupation extends BaseOccupation<Occupation> {
	
}
