package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseOrganization;

/**
 * Generated by Jboot.
 */
@Table(tableName = "organization", primaryKey = "id")
public class Organization extends BaseOrganization<Organization> {
	
}
