package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseOrgStructure;

/**
 * Generated by Jboot.
 */
@Table(tableName = "org_structure", primaryKey = "id")
public class OrgStructure extends BaseOrgStructure<OrgStructure> {
	
}
