package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BasePoliticalStatus;

/**
 * Generated by Jboot.
 */
@Table(tableName = "political_status", primaryKey = "id")
public class PoliticalStatus extends BasePoliticalStatus<PoliticalStatus> {
	
}
