package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BasePost;

/**
 * Generated by Jboot.
 */
@Table(tableName = "post", primaryKey = "id")
public class Post extends BasePost<Post> {
	
}
