package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseProAssReview;

/**
 * Generated by Jboot.
 */
@Table(tableName = "pro_ass_review", primaryKey = "id")
public class ProAssReview extends BaseProAssReview<ProAssReview> {

}
