package io.jboot.admin.service.entity.model;

import io.jboot.admin.service.entity.status.system.DataStatus;
import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseProAssReview;

/**
 * Generated by Jboot.
 */
@Table(tableName = "pro_ass_review", primaryKey = "id")
public class ProAssReview extends BaseProAssReview<ProAssReview> {
    public void setStatus(java.lang.String status) {
        if (status.equals(DataStatus.USED)) {
            setIsEnable(true);
        } else {
            setIsEnable(false);
        }
    }

    public java.lang.String getStatus() {
        if (this.getIsEnable()) {
            return DataStatus.USED;
        } else {
            return DataStatus.UNUSED;
        }
    }
}
