package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseProfGroup;

/**
 * Generated by Jboot.
 */
@Table(tableName = "prof_group", primaryKey = "id")
public class ProfGroup extends BaseProfGroup<ProfGroup> {

    private boolean isInvite;

    public void setIsInvite(boolean isInvite) {
        this.isInvite = isInvite;
    }

    public boolean getIsInvite() {
        return this.isInvite;
    }
}
