package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseProjectUndertake;

/**
 * Generated by Jboot.
 */
@Table(tableName = "project_undertake", primaryKey = "id")
public class ProjectUndertake extends BaseProjectUndertake<ProjectUndertake> {
    private Project project;
    private FacAgency facAgency;
    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    public String getProjectAssTypeName()
    {
        if(null != project){
            return this.project.getProjectAssTypeName();
        }
        return "";
    }

    public String getProjectAssessmentMode()
    {
        if(null != project){
            return this.project.getAssessmentMode();
        }
        return "";
    }

    public FacAgency getFacAgency() {
        return facAgency;
    }

    public void setFacAgency(FacAgency facAgency) {
        this.facAgency = facAgency;
    }

    public String getFacAgencyName()
    {
        if(null != facAgency){
            return this.facAgency.getName();
        }
        return "";
    }
}
