package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseProjectExpertgroup;

/**
 * Generated by Jboot.
 */
@Table(tableName = "project_expertgroup", primaryKey = "id")
public class ProjectExpertgroup extends BaseProjectExpertgroup<ProjectExpertgroup> {

}
