package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseProject;

/**
 * Generated by Jboot.
 */
@Table(tableName = "project", primaryKey = "id")
public class Project extends BaseProject<Project> {
    private String typeName;
    private String reply;
    private boolean isReceive;
    private double maxAmount;
    private double minAmount;
    private boolean isUpload;
    private Long fileID;
    private ProjectAssType projectAssType;
    private String buildOrgName;
    private String buildUserName;
    private String facAgencyName;
    private boolean isBackRecordUpLoad;
    private boolean isBackRecordTransferUpLoad;
    private boolean isRiskTrackUpLoad;
    private Long backRecordFileID;
    private Long backRecordTransferFileID;
    private String reviewInfo;
    private Integer ownType;
    private Integer assessmentProgress; //评估进度

    public Management getManagement() {
        return management;
    }

    public void setManagement(Management management) {
        this.management = management;
    }

    private Management management; //管理部门

    public String getManagementName() {
        if(null != this.management)
            return this.management.getName();
        else
            return "未指定管理部门";
    }

    public String getFacAgencyName() {
        return facAgencyName;
    }

    public void setFacAgencyName(String facAgencyName) {
        this.facAgencyName = facAgencyName;
    }

    public void setManagementName(String managementName) {
        this.managementName = managementName;
    }

    private String managementName; //管理部门

    public boolean isBackRecordTransferUpLoad() {
        return isBackRecordTransferUpLoad;
    }

    public void setBackRecordTransferUpLoad(boolean backRecordTransferUpLoad) {
        isBackRecordTransferUpLoad = backRecordTransferUpLoad;
    }

    public Long getBackRecordTransferFileID() {
        return backRecordTransferFileID;
    }

    public void setBackRecordTransferFileID(Long backRecordTransferFileID) {
        this.backRecordTransferFileID = backRecordTransferFileID;
    }


    public String getReviewInfo() {
        StringBuilder sbInfo = new StringBuilder();
        sbInfo.append("邀请人数：");
        sbInfo.append(getInviteReviewCount());
        if(getPassReviewCount() > 0)
        {
            sbInfo.append("，审查通过人数：");
            sbInfo.append(getPassReviewCount());
        }
        if(getPassReviewByOverdueCount() > 0)
        {
            sbInfo.append("，超时默认审查通过人数：");
            sbInfo.append(getPassReviewByOverdueCount());
        }
        return sbInfo.toString();
    }

    public ProjectAssType getProjectAssType() {
        return this.projectAssType;
    }

    public void setProjectAssType(ProjectAssType projectAssType) {
        this.projectAssType = projectAssType;
    }

    public String getProjectAssTypeName()
    {
        if(null != projectAssType){
            return this.projectAssType.getName();
        }
        return "";
    }

    public Long getFileID() {
        return fileID;
    }

    public void setFileID(Long fileID) {
        this.fileID = fileID;
    }

    public boolean getIsUpload() {
        return isUpload;
    }

    public void setIsUpload(boolean isUpload) {
        this.isUpload = isUpload;
    }

    public double getMaxAmount() {
        return maxAmount;
    }

    public void setMaxAmount(double maxAmount) {
        this.maxAmount = maxAmount;
    }

    public double getMinAmount() {
        return minAmount;
    }

    public void setMinAmount(double minAmount) {
        this.minAmount = minAmount;
    }

    public boolean getIsReceive() {
        return isReceive;
    }

    public void setIsReceive(boolean isReceive) {
        this.isReceive = isReceive;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public void setReply(String reply) {
        this.reply = reply;
    }

    public String getBuildOrgName() {
        return buildOrgName;
    }

    public void setBuildOrgName(String buildOrgName) {
        this.buildOrgName = buildOrgName;
    }

    public String getBuildUserName() {
        return buildUserName;
    }

    public void setBuildUserName(String buildUserName) {
        this.buildUserName = buildUserName;
    }

    public boolean getIsBackRecordUpLoad() {
        return isBackRecordUpLoad;
    }

    public void setIsBackRecordUpLoad(boolean backRecordUpLoad) {
        isBackRecordUpLoad = backRecordUpLoad;
    }

    public Long getBackRecordFileID() {
        return backRecordFileID;
    }

    public void setBackRecordFileID(Long backRecordFileID) {
        this.backRecordFileID = backRecordFileID;
    }

    public boolean getIsRiskTrackUpLoad() {
        return isRiskTrackUpLoad;
    }

    public void setIsRiskTrackUpLoad(boolean riskTrackUpLoad) {
        isRiskTrackUpLoad = riskTrackUpLoad;
    }

    public Integer getOwnType() {
        return ownType;
    }

    public void setOwnType(Integer ownType) {
        this.ownType = ownType;
    }

    public Integer getAssessmentProgress() {
        assessmentProgress = (int)Math.floor(this.getProgress() / 17.0 * 100);
        return assessmentProgress;
    }
}