package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseProject;

/**
 * Generated by Jboot.
 */
@Table(tableName = "project", primaryKey = "id")
public class Project extends BaseProject<Project> {
    private String typeName;
    private String reply;
    private boolean isReceive;
    private double maxAmount;
    private double minAmount;
    private boolean isUpload;
    private Long fileID;
    private ProjectAssType projectAssType;
    private String buildOrgName;
    private String buildUserName;
    private boolean isBackRecordUpLoad;
    private boolean isRiskTrackUpLoad;
    private Long backRecordFileID;
    private String reviewInfo;
    private Integer ownType;
    /**
     * 评估进度
     */
    private String assessmentProgress;

    public String getReviewInfo() {
        StringBuilder sbInfo = new StringBuilder();
        sbInfo.append("邀请人数：");
        sbInfo.append(getInviteReviewCount());
        if(getPassReviewCount() > 0)
        {
            sbInfo.append("，审查通过人数：");
            sbInfo.append(getPassReviewCount());
        }
        if(getPassReviewByOverdueCount() > 0)
        {
            sbInfo.append("，超时默认审查通过人数：");
            sbInfo.append(getPassReviewByOverdueCount());
        }
        return sbInfo.toString();
    }

    public ProjectAssType getProjectAssType() {
        return this.projectAssType;
    }

    public void setProjectAssType(ProjectAssType projectAssType) {
        this.projectAssType = projectAssType;
    }

    public String getProjectAssTypeName()
    {
        if(null != projectAssType){
            return this.projectAssType.getName();
        }
        return "";
    }

    public Long getFileID() {
        return fileID;
    }

    public void setFileID(Long fileID) {
        this.fileID = fileID;
    }

    public boolean getIsUpload() {
        return isUpload;
    }

    public void setIsUpload(boolean isUpload) {
        this.isUpload = isUpload;
    }

    public double getMaxAmount() {
        return maxAmount;
    }

    public void setMaxAmount(double maxAmount) {
        this.maxAmount = maxAmount;
    }

    public double getMinAmount() {
        return minAmount;
    }

    public void setMinAmount(double minAmount) {
        this.minAmount = minAmount;
    }

    public boolean getIsReceive() {
        return isReceive;
    }

    public void setIsReceive(boolean isReceive) {
        this.isReceive = isReceive;
    }

    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public void setReply(String reply) {
        this.reply = reply;
    }

    public String getBuildOrgName() {
        return buildOrgName;
    }

    public void setBuildOrgName(String buildOrgName) {
        this.buildOrgName = buildOrgName;
    }

    public String getBuildUserName() {
        return buildUserName;
    }

    public void setBuildUserName(String buildUserName) {
        this.buildUserName = buildUserName;
    }

    public boolean getIsBackRecordUpLoad() {
        return isBackRecordUpLoad;
    }

    public void setIsBackRecordUpLoad(boolean backRecordUpLoad) {
        isBackRecordUpLoad = backRecordUpLoad;
    }

    public Long getBackRecordFileID() {
        return backRecordFileID;
    }

    public void setBackRecordFileID(Long backRecordFileID) {
        this.backRecordFileID = backRecordFileID;
    }

    public boolean getIsRiskTrackUpLoad() {
        return isRiskTrackUpLoad;
    }

    public void setIsRiskTrackUpLoad(boolean riskTrackUpLoad) {
        isRiskTrackUpLoad = riskTrackUpLoad;
    }

    public Integer getOwnType() {
        return ownType;
    }

    public void setOwnType(Integer ownType) {
        this.ownType = ownType;
    }

    public String getAssessmentProgress() {
        return assessmentProgress;
    }

    public void setAssessmentProgress(String assessmentProgress) {
        this.assessmentProgress = assessmentProgress;
    }

}