package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseProjectFileType;

/**
 * Generated by Jboot.
 */
@Table(tableName = "project_file_type", primaryKey = "id")
public class ProjectFileType extends BaseProjectFileType<ProjectFileType> {
	
}
