package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseProjectUndertake;

/**
 * Generated by Jboot.
 */
@Table(tableName = "project_undertake", primaryKey = "id")
public class ProjectUndertake extends BaseProjectUndertake<ProjectUndertake> {
	
}
