package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseProjectType;

/**
 * Generated by Jboot.
 */
@Table(tableName = "project_type", primaryKey = "id")
public class ProjectType extends BaseProjectType<ProjectType> {
	
}
