package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseProjectAssType;

/**
 * Generated by Jboot.
 */
@Table(tableName = "project_ass_type", primaryKey = "id")
public class ProjectAssType extends BaseProjectAssType<ProjectAssType> {
	
}
