package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseProjectFileType;

/**
 * Generated by Jboot.
 */
@Table(tableName = "project_file_type", primaryKey = "id")
public class ProjectFileType extends BaseProjectFileType<ProjectFileType> {

    Boolean isUpLoad = false;

    Long fileID;

    public Long getFileID() {
        return fileID;
    }

    public void setFileID(Long fileID) {
        this.fileID = fileID;
    }

    public boolean getIsUpLoad() {
        return isUpLoad;
    }

    public void setIsUpLoad(boolean upLoad) {
        isUpLoad = upLoad;
    }

}
