package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseProjectUndertake;

/**
 * Generated by Jboot.
 */
@Table(tableName = "project_undertake", primaryKey = "id")
public class ProjectUndertake extends BaseProjectUndertake<ProjectUndertake> {
    private Project project;

    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    public String getProjectAssTypeName()
    {
        if(null != project){
            return this.project.getProjectAssTypeName();
        }
        return "";
    }

//    public static final ProjectUndertake dao = new ProjectUndertake();
//
//    public ProjectType getProjectType() {
//        return ProjectType.dao.findById(new Object[]{get("projectID")});
//    }
}
