package io.jboot.admin.service.entity.model;

import io.jboot.admin.service.entity.status.system.DataStatus;
import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseProjectAssType;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by Jboot.
 */
@Table(tableName = "project_ass_type", primaryKey = "id")
public class ProjectAssType extends BaseProjectAssType<ProjectAssType> {
    public static final ProjectAssType dao = new ProjectAssType().dao();

    public void setStatus(java.lang.String status) {
        if (status == DataStatus.USED) {
            setIsEnable(true);
        } else {
            setIsEnable(false);
        }
    }

    public java.lang.String getStatus() {
        if(this.getIsEnable() == true)
            return DataStatus.USED;
        else
            return DataStatus.UNUSED;
    }
}
