package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseQuestionnaire;

/**
 * Generated by Jboot.
 */
@Table(tableName = "questionnaire", primaryKey = "id")
public class Questionnaire extends BaseQuestionnaire<Questionnaire> {
	
}
