package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseQuestionnaireContentLink;

/**
 * Generated by Jboot.
 */
@Table(tableName = "questionnaire_content_link", primaryKey = "id")
public class QuestionnaireContentLink extends BaseQuestionnaireContentLink<QuestionnaireContentLink> {
	
}
