package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseQuestionnaireContent;

/**
 * Generated by Jboot.
 */
@Table(tableName = "questionnaire_content", primaryKey = "id")
public class QuestionnaireContent extends BaseQuestionnaireContent<QuestionnaireContent> {
	
}
