package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseQuestionnaireFiles;

/**
 * Generated by Jboot.
 */
@Table(tableName = "questionnaire_files", primaryKey = "id")
public class QuestionnaireFiles extends BaseQuestionnaireFiles<QuestionnaireFiles> {
	
}
