package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseRejectProjectInfo;

/**
 * Generated by Jboot.
 */
@Table(tableName = "reject_project_info", primaryKey = "id")
public class RejectProjectInfo extends BaseRejectProjectInfo<RejectProjectInfo> {
	
}
