package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseRes1;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_res1", primaryKey = "id")
public class Res1 extends BaseRes1<Res1> {
	
}
