package io.jboot.admin.service.entity.model;

import io.jboot.admin.service.entity.status.system.DataStatus;
import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseRiskPoint;

/**
 * Generated by Jboot.
 */
@Table(tableName = "risk_point", primaryKey = "id")
public class RiskPoint extends BaseRiskPoint<RiskPoint> {
    private Project project;
    public Project getProject() {
        return project;
    }

    public void setProject(Project project) {
        this.project = project;
    }

    public String getProjectName()
    {
        if(null != project){
            return this.project.getName();
        }
        return "";
    }

    public void setStatus(java.lang.String status) {
        if (status == DataStatus.USED) {
            setIsEnable(true);
        } else {
            setIsEnable(false);
        }
    }

    public java.lang.String getStatus() {
        if(this.getIsEnable() == true)
            return DataStatus.USED;
        else
            return DataStatus.UNUSED;
    }
	
}
