package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseRole1;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_role1", primaryKey = "id")
public class Role1 extends BaseRole1<Role1> {
	
}
