package io.jboot.admin.service.entity.model;

import io.jboot.admin.service.entity.status.system.ResStatus;
import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseRole;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_role", primaryKey = "id")
public class Role extends BaseRole<Role> {
    public void setStatus(java.lang.String status) {
        if (status == ResStatus.USED) {
            setIsEnable(true);
        } else {
            setIsEnable(false);
        }
    }

    public java.lang.String getStatus() {
        if(this.getIsEnable() == true)
            return ResStatus.USED;
        else
            return ResStatus.UNUSED;
    }
	
}
