package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseRoleRes1;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_role_res1", primaryKey = "id")
public class RoleRes1 extends BaseRoleRes1<RoleRes1> {
	
}
