package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseScheduledPlan;

/**
 * Generated by Jboot.
 */
@Table(tableName = "scheduled_plan", primaryKey = "id")
public class ScheduledPlan extends BaseScheduledPlan<ScheduledPlan> {

}
