package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseSiteSurveyExpertAdvice;

/**
 * Generated by Jboot.
 */
@Table(tableName = "site_survey_expert_advice", primaryKey = "id")
public class SiteSurveyExpertAdvice extends BaseSiteSurveyExpertAdvice<SiteSurveyExpertAdvice> {
	
}
