package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseSiteSurveyExpertAdvice;

/**
 * Generated by Jboot.
 */
@Table(tableName = "site_survey_expert_advice", primaryKey = "id")
public class SiteSurveyExpertAdvice extends BaseSiteSurveyExpertAdvice<SiteSurveyExpertAdvice> {
    /**
     * 获取专家姓名
     * @return 专家姓名
     */
    public String getExpertName() {
        return expertName;
    }

    /**
     * 设置专家姓名
     * @param expertName 新的专家姓名
     */
    public void setExpertName(String expertName) {
        this.expertName = expertName;
    }

    private String expertName;//专家姓名
}
