package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseStructPersonLink;

/**
 * Generated by Jboot.
 */
@Table(tableName = "struct_person_link", primaryKey = "ID")
public class StructPersonLink extends BaseStructPersonLink<StructPersonLink> {

}
