package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseUserRole1;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_user_role1", primaryKey = "id")
public class UserRole1 extends BaseUserRole1<UserRole1> {
	
}
