package io.jboot.admin.service.entity.model;

import io.jboot.db.annotation.Table;
import io.jboot.admin.service.entity.model.base.BaseUser1;

/**
 * Generated by Jboot.
 */
@Table(tableName = "sys_user1", primaryKey = "id")
public class User1 extends BaseUser1<User1> {
	
}
