package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAuthProject<M extends BaseAuthProject<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setUserId(java.lang.Long userId) {
		set("userId", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("userId");
	}

	public void setRoleId(java.lang.Long roleId) {
		set("roleId", roleId);
	}
	
	public java.lang.Long getRoleId() {
		return getLong("roleId");
	}

	public void setProjectId(java.lang.Long projectId) {
		set("projectId", projectId);
	}
	
	public java.lang.Long getProjectId() {
		return getLong("projectId");
	}

	public void setReply(java.lang.String reply) {
		set("reply", reply);
	}
	
	public java.lang.String getReply() {
		return getStr("reply");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}

	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setLastUpdTime(java.util.Date lastUpdTime) {
		set("lastUpdTime", lastUpdTime);
	}
	
	public java.util.Date getLastUpdTime() {
		return get("lastUpdTime");
	}

	public void setLastUpdUser(java.lang.String lastUpdUser) {
		set("lastUpdUser", lastUpdUser);
	}
	
	public java.lang.String getLastUpdUser() {
		return getStr("lastUpdUser");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
