package io.jboot.admin.service.entity.model.base;

import com.sun.org.apache.xpath.internal.operations.Bool;
import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProAssReview<M extends BaseProAssReview<M>> extends JbootModel<M> implements IBean {

	public void setId(Long id) {
		set("id", id);
	}
	
	public Long getId() {
		return getLong("id");
	}

	public void setName(String name) {
		set("name", name);
	}
	
	public String getName() {
		return getStr("name");
	}

	public void setSpell(String spell) {
		set("spell", spell);
	}
	
	public String getSpell() {
		return getStr("spell");
	}

	public void setProjectID(Long projectID) {
		set("projectID", projectID);
	}
	
	public Long getProjectID() {
		return getLong("projectID");
	}

	public void setReviewerID(Long reviewerID) {
		set("reviewerID", reviewerID);
	}
	
	public Long getReviewerID() {
		return getLong("reviewerID");
	}

	public void setRecomment(String recomment) {
		set("recomment", recomment);
	}
	
	public String getRecomment() {
		return getStr("recomment");
	}

	public void setFeedback(String feedback) {
		set("feedback", feedback);
	}
	
	public String getFeedback() {
		return getStr("feedback");
	}

	public void setFileID(Long fileID) {
		set("fileID", fileID);
	}
	
	public Long getFileID() {
		return getLong("fileID");
	}

	public void setReviewStatus(Integer reviewStatus) {
		set("reviewStatus", reviewStatus);
	}
	
	public Integer getReviewStatus() {
		return getInt("reviewStatus");
	}

	public void setIsPass(Integer isPass) {
		set("isPass", isPass);
	}
	
	public Integer getIsPass() {
		return getInt("isPass");
	}

	public void setCreateUserID(Long createUserID) {
		set("createUserID", createUserID);
	}
	
	public Long getCreateUserID() {
		return getLong("createUserID");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setLastUpdateUserID(Long lastUpdateUserID) {
		set("lastUpdateUserID", lastUpdateUserID);
	}
	
	public Long getLastUpdateUserID() {
		return getLong("lastUpdateUserID");
	}

	public void setLastAccessTime(java.util.Date lastAccessTime) {
		set("lastAccessTime", lastAccessTime);
	}
	
	public java.util.Date getLastAccessTime() {
		return get("lastAccessTime");
	}

	public void setSort(Integer sort) {
		set("sort", sort);
	}
	
	public Integer getSort() {
		return getInt("sort");
	}

	public void setRemark(String remark) {
		set("remark", remark);
	}
	
	public String getRemark() {
		return getStr("remark");
	}

	public void setIsEnable(Boolean isEnable) {
		set("isEnable", isEnable);
	}
	
	public Boolean getIsEnable() {
		return getBoolean("isEnable");
	}

}
