package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseExpertGroup<M extends BaseExpertGroup<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setSpell(java.lang.String spell) {
		set("spell", spell);
	}
	
	public java.lang.String getSpell() {
		return getStr("spell");
	}

	public void setAffectedGroupID(java.lang.Long affectedGroupID) {
		set("affectedGroupID", affectedGroupID);
	}
	
	public java.lang.Long getAffectedGroupID() {
		return getLong("affectedGroupID");
	}

	public void setPersonID(java.lang.Long personID) {
		set("personID", personID);
	}
	
	public java.lang.Long getPersonID() {
		return getLong("personID");
	}

	public void setWorktime(java.util.Date worktime) {
		set("worktime", worktime);
	}
	
	public java.util.Date getWorktime() {
		return get("worktime");
	}

	public void setWorkstate(java.lang.String workstate) {
		set("workstate", workstate);
	}
	
	public java.lang.String getWorkstate() {
		return getStr("workstate");
	}

	public void setProfess(java.lang.String profess) {
		set("profess", profess);
	}
	
	public java.lang.String getProfess() {
		return getStr("profess");
	}

	public void setCertificate(java.lang.String certificate) {
		set("certificate", certificate);
	}
	
	public java.lang.String getCertificate() {
		return getStr("certificate");
	}

	public void setDepartment(java.lang.String department) {
		set("department", department);
	}
	
	public java.lang.String getDepartment() {
		return getStr("department");
	}

	public void setWorkpictrue(java.lang.String workpictrue) {
		set("workpictrue", workpictrue);
	}
	
	public java.lang.String getWorkpictrue() {
		return getStr("workpictrue");
	}

	public void setProject(java.lang.String project) {
		set("project", project);
	}
	
	public java.lang.String getProject() {
		return getStr("project");
	}

	public void setCreateUserID(java.lang.Long createUserID) {
		set("createUserID", createUserID);
	}
	
	public java.lang.Long getCreateUserID() {
		return getLong("createUserID");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setLastUpdateUserID(java.lang.Long lastUpdateUserID) {
		set("lastUpdateUserID", lastUpdateUserID);
	}
	
	public java.lang.Long getLastUpdateUserID() {
		return getLong("lastUpdateUserID");
	}

	public void setLastAccessTime(java.util.Date lastAccessTime) {
		set("lastAccessTime", lastAccessTime);
	}
	
	public java.util.Date getLastAccessTime() {
		return get("lastAccessTime");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setIsEnable(java.lang.Integer isEnable) {
		set("isEnable", isEnable);
	}
	
	public java.lang.Integer getIsEnable() {
		return getInt("isEnable");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

}
