package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAuth<M extends BaseAuth<M>> extends JbootModel<M> implements IBean {

	public void setId(java.math.BigInteger id) {
		set("id", id);
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public void setUserId(java.lang.Long userId) {
		set("userId", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("userId");
	}

	public void setRoleId(java.lang.Long roleId) {
		set("roleId", roleId);
	}
	
	public java.lang.Long getRoleId() {
		return getLong("roleId");
	}

	public void setReply(java.lang.String reply) {
		set("reply", reply);
	}
	
	public java.lang.String getReply() {
		return getStr("reply");
	}

	public void setLastUpdTime(java.util.Date lastUpdTime) {
		set("lastUpdTime", lastUpdTime);
	}
	
	public java.util.Date getLastUpdTime() {
		return get("lastUpdTime");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

    public void setType(java.lang.String type) {
        set("type", type);
    }

    public java.lang.String getType() {
        return getStr("type");
    }

}
