package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseManagement<M extends BaseManagement<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setSpell(java.lang.String spell) {
		set("spell", spell);
	}
	
	public java.lang.String getSpell() {
		return getStr("spell");
	}

	public void setOrgID(java.lang.Long orgID) {
		set("orgID", orgID);
	}
	
	public java.lang.Long getOrgID() {
		return getLong("orgID");
	}

	public void setResponsibility(java.lang.String responsibility) {
		set("responsibility", responsibility);
	}
	
	public java.lang.String getResponsibility() {
		return getStr("responsibility");
	}

	public void setSuperior(java.lang.String superior) {
		set("superior", superior);
	}
	
	public java.lang.String getSuperior() {
		return getStr("superior");
	}

	public void setPrincipal(java.lang.String principal) {
		set("principal", principal);
	}
	
	public java.lang.String getPrincipal() {
		return getStr("principal");
	}

	public void setPrincipalcon(java.lang.String principalcon) {
		set("principalcon", principalcon);
	}
	
	public java.lang.String getPrincipalcon() {
		return getStr("principalcon");
	}

	public void setParty(java.lang.String party) {
		set("party", party);
	}
	
	public java.lang.String getParty() {
		return getStr("party");
	}

	public void setManager(java.lang.String manager) {
		set("manager", manager);
	}
	
	public java.lang.String getManager() {
		return getStr("manager");
	}

	public void setManagercon(java.lang.String managercon) {
		set("managercon", managercon);
	}
	
	public java.lang.String getManagercon() {
		return getStr("managercon");
	}

	public void setDetailedaddr(java.lang.String detailedaddr) {
		set("detailedaddr", detailedaddr);
	}
	
	public java.lang.String getDetailedaddr() {
		return getStr("detailedaddr");
	}

	public void setNum(java.lang.Integer num) {
		set("num", num);
	}
	
	public java.lang.Integer getNum() {
		return getInt("num");
	}

	public void setLower(java.lang.String lower) {
		set("lower", lower);
	}
	
	public java.lang.String getLower() {
		return getStr("lower");
	}

	public void setCreateUserID(java.lang.Long createUserID) {
		set("createUserID", createUserID);
	}
	
	public java.lang.Long getCreateUserID() {
		return getLong("createUserID");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setLastUpdateUserID(java.lang.Long lastUpdateUserID) {
		set("lastUpdateUserID", lastUpdateUserID);
	}
	
	public java.lang.Long getLastUpdateUserID() {
		return getLong("lastUpdateUserID");
	}

	public void setLastAccessTime(java.util.Date lastAccessTime) {
		set("lastAccessTime", lastAccessTime);
	}
	
	public java.util.Date getLastAccessTime() {
		return get("lastAccessTime");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setIsEnable(java.lang.Boolean isEnable) {
		set("isEnable", isEnable);
	}
	
	public java.lang.Boolean getIsEnable() {
		return get("isEnable");
	}

}
