package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNews<M extends BaseNews<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setSpell(java.lang.String spell) {
		set("spell", spell);
	}
	
	public java.lang.String getSpell() {
		return getStr("spell");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

	public void setPublishTime(java.util.Date publishTime) {
		set("publishTime", publishTime);
	}
	
	public java.util.Date getPublishTime() {
		return get("publishTime");
	}

	public void setNewsletter(java.lang.String newsletter) {
		set("newsletter", newsletter);
	}
	
	public java.lang.String getNewsletter() {
		return getStr("newsletter");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setType(java.lang.Integer type) {
		set("type", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("type");
	}

	public void setPublisherID(java.lang.Long publisherID) {
		set("publisherID", publisherID);
	}
	
	public java.lang.Long getPublisherID() {
		return getLong("publisherID");
	}

	public void setSource(java.lang.String source) {
		set("source", source);
	}
	
	public java.lang.String getSource() {
		return getStr("source");
	}

	public void setEditer(java.lang.String editer) {
		set("editer", editer);
	}
	
	public java.lang.String getEditer() {
		return getStr("editer");
	}

	public void setRespEditer(java.lang.String respEditer) {
		set("respEditer", respEditer);
	}
	
	public java.lang.String getRespEditer() {
		return getStr("respEditer");
	}

	public void setIsPublish(java.lang.Integer isPublish) {
		set("isPublish", isPublish);
	}
	
	public java.lang.Integer getIsPublish() {
		return getInt("isPublish");
	}

	public void setReceiverRoles(java.lang.String receiverRoles) {
		set("receiverRoles", receiverRoles);
	}
	
	public java.lang.String getReceiverRoles() {
		return getStr("receiverRoles");
	}

	public void setReceiverUsers(java.lang.String receiverUsers) {
		set("receiverUsers", receiverUsers);
	}
	
	public java.lang.String getReceiverUsers() {
		return getStr("receiverUsers");
	}

	public void setCreateUserID(java.lang.Long createUserID) {
		set("createUserID", createUserID);
	}
	
	public java.lang.Long getCreateUserID() {
		return getLong("createUserID");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setLastUpdateUserID(java.lang.Long lastUpdateUserID) {
		set("lastUpdateUserID", lastUpdateUserID);
	}
	
	public java.lang.Long getLastUpdateUserID() {
		return getLong("lastUpdateUserID");
	}

	public void setLastAccessTime(java.util.Date lastAccessTime) {
		set("lastAccessTime", lastAccessTime);
	}
	
	public java.util.Date getLastAccessTime() {
		return get("lastAccessTime");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setIsEnable(java.lang.Boolean isEnable) {
		set("isEnable", isEnable);
	}
	
	public java.lang.Boolean getIsEnable() {
		return get("isEnable");
	}

}
