package io.jboot.admin.service.entity.model.base;

import io.jboot.db.model.JbootModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by Jboot, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseProject<M extends BaseProject<M>> extends JbootModel<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setSpell(java.lang.String spell) {
		set("spell", spell);
	}
	
	public java.lang.String getSpell() {
		return getStr("spell");
	}

	public void setUserId(java.lang.Long userId) {
		set("userId", userId);
	}
	
	public java.lang.Long getUserId() {
		return getLong("userId");
	}

	public void setRoleName(java.lang.String roleName) {
		set("roleName", roleName);
	}
	
	public java.lang.String getRoleName() {
		return getStr("roleName");
	}

	public void setAmount(java.lang.Double amount) {
		set("amount", amount);
	}
	
	public java.lang.Double getAmount() {
		return getDouble("amount");
	}

	public void setPaTypeID(java.lang.Long paTypeID) {
		set("paTypeID", paTypeID);
	}
	
	public java.lang.Long getPaTypeID() {
		return getLong("paTypeID");
	}

	public void setPStepID(java.lang.Long pStepID) {
		set("pStepID", pStepID);
	}
	
	public java.lang.Long getPStepID() {
		return getLong("pStepID");
	}

	public void setSite(java.lang.String site) {
		set("site", site);
	}
	
	public java.lang.String getSite() {
		return getStr("site");
	}

	public void setBrief(java.lang.String brief) {
		set("brief", brief);
	}
	
	public java.lang.String getBrief() {
		return getStr("brief");
	}

	public void setAssessmentMode(java.lang.String assessmentMode) {
		set("assessmentMode", assessmentMode);
	}
	
	public java.lang.String getAssessmentMode() {
		return getStr("assessmentMode");
	}

	public void setStatus(java.lang.String status) {
		set("status", status);
	}
	
	public java.lang.String getStatus() {
		return getStr("status");
	}

	public void setIsPublic(java.lang.Boolean isPublic) {
		set("isPublic", isPublic);
	}
	
	public java.lang.Boolean getIsPublic() {
		return get("isPublic");
	}

	public void setTag(java.lang.String tag) {
		set("tag", tag);
	}
	
	public java.lang.String getTag() {
		return getStr("tag");
	}

	public void setPublicTime(java.util.Date publicTime) {
		set("publicTime", publicTime);
	}
	
	public java.util.Date getPublicTime() {
		return get("publicTime");
	}

	public void setEndPublicTime(java.util.Date endPublicTime) {
		set("endPublicTime", endPublicTime);
	}
	
	public java.util.Date getEndPublicTime() {
		return get("endPublicTime");
	}

	public void setInviteReviewCount(java.lang.Integer inviteReviewCount) {
		set("inviteReviewCount", inviteReviewCount);
	}
	
	public java.lang.Integer getInviteReviewCount() {
		return getInt("inviteReviewCount");
	}

	public void setAgreeReviewCount(java.lang.Integer agreeReviewCount) {
		set("agreeReviewCount", agreeReviewCount);
	}
	
	public java.lang.Integer getAgreeReviewCount() {
		return getInt("agreeReviewCount");
	}

	public void setRefuseReviewCount(java.lang.Integer refuseReviewCount) {
		set("refuseReviewCount", refuseReviewCount);
	}
	
	public java.lang.Integer getRefuseReviewCount() {
		return getInt("refuseReviewCount");
	}

	public void setPassReviewCount(java.lang.Integer passReviewCount) {
		set("passReviewCount", passReviewCount);
	}
	
	public java.lang.Integer getPassReviewCount() {
		return getInt("passReviewCount");
	}

	public void setUnpassReviewCount(java.lang.Integer unpassReviewCount) {
		set("unpassReviewCount", unpassReviewCount);
	}
	
	public java.lang.Integer getUnpassReviewCount() {
		return getInt("unpassReviewCount");
	}

    public void setPassReviewByOverdueCount(java.lang.Long passReviewByOverdueCount) {
        set("passReviewByOverdueCount", passReviewByOverdueCount);
    }

    public java.lang.Long getPassReviewByOverdueCount() {
		return getLong("passReviewByOverdueCount");
	}

	public void setCreateUserID(java.lang.Long createUserID) {
		set("createUserID", createUserID);
	}
	
	public java.lang.Long getCreateUserID() {
		return getLong("createUserID");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setLastUpdateUserID(java.lang.Long lastUpdateUserID) {
		set("lastUpdateUserID", lastUpdateUserID);
	}
	
	public java.lang.Long getLastUpdateUserID() {
		return getLong("lastUpdateUserID");
	}

	public void setLastAccessTime(java.util.Date lastAccessTime) {
		set("lastAccessTime", lastAccessTime);
	}
	
	public java.util.Date getLastAccessTime() {
		return get("lastAccessTime");
	}

	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}
	
	public java.lang.Integer getSort() {
		return getInt("sort");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public void setIsEnable(java.lang.Boolean isEnable) {
		set("isEnable", isEnable);
	}
	
	public java.lang.Boolean getIsEnable() {
		return get("isEnable");
	}

	public void setManagementID(java.lang.Long managementID) {
		set("managementID", managementID);
	}
	
	public java.lang.Long getManagementID() {
		return getLong("managementID");
	}

}
